sudo: false
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: true
node_js:
- '8'
after_success:
- npm run prepare-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"